### ISSUE TITLE
Style error on extensions.contao.org

### ISSUE THREAD

**Issue by xchs** [contao/package-list#1]
**Affected version(s)**

**Description**
There is a small style error on the website https://extensions.contao.org/

![contao_extensions](https://user-images.githubusercontent.com/1218766/66595566-8415f300-eb9b-11e9-9151-c03857464f2b.png)

Increasing the line height to e.g. 1.4 should fix it:
```css
.layout-main__logo p {
    …
    line-height: 1.4;
}
```

**How to reproduce**  
* Go to https://extensions.contao.org/
